### ISSUE TITLE
Tiles ETS: outdated test

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ets-ogcapi-tiles10#2]
This [text case](https://github.com/opengeospatial/ets-ogcapi-tiles10/blob/641caeaaca102e3d4d8929e803cd8bc8bf8274d0/src/main/java/org/opengis/cite/ogcapitiles10/tileset/TileSet.java#L68) seems to be outdated. I do not see why it does what it does and how this relates to the spec.

**Comment by dstenger** [comment]
I can confirm that this test is outdated and not covered by the standard anymore.

**Comment by dstenger** [comment]
Same branch as in https://github.com/opengeospatial/ets-ogcapi-tiles10/issues/5#issuecomment-1332391215 is used.

**Comment by dstenger** [comment]
Test was removed from test suite: https://github.com/opengeospatial/ets-ogcapi-tiles10/commit/9210c301c4117e934ddaa7c5ddb394f0f070b68d
