### ISSUE TITLE
Validation of requirement 11

### ISSUE THREAD

**Issue by doublebyte1** [opengeospatial/ets-ogcapi-tiles10#30]
**Describe the bug**
The ETS  expects Dataset Tilesets, which [according to the spec are not a core requirement](https://docs.ogc.org/is/20-057/20-057.html#toc40). See the discussion [here](https://github.com/opengeospatial/ogcapi-tiles/issues/169). 

**To Reproduce**
Run the tests for a server that does not implement dataset tilesets:

https://maps.gnosis.earth/ogcapi/?f=json
https://demo.pygeoapi.io/master/?f=json

The ets produces an error.

**Expected behavior**
These servers do not claim to support dataset tilesets in the conformance declaration, and should not be tested for it. Instead they support collection tilesets.

**Additional context**
https://github.com/geopython/pygeoapi/issues/1728#issuecomment-2303350194

**Comment by dstenger** [comment]
Thanks for reporting.
Can you please check if pull request https://github.com/opengeospatial/ets-ogcapi-tiles10/pull/29 solves your problem?

**Comment by doublebyte1** [comment]
@dstenger I think Tom [tested it ](https://github.com/geopython/pygeoapi/issues/1728#issuecomment-2307460123)and it works fine now! Closing the issue, now. Thank you 🙏🏽
